version: "3.9"

services:
  db:
    image: mysql:8
    container_name: barberboss-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "@Password123"
      MYSQL_DATABASE: barberbossdb
    ports:
      - "3306:3306"
    profiles: ["prod"]   
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p@Password123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barberboss-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
    depends_on:
      db:
        condition: service_healthy
    profiles: ["prod", "dev"]  
