name: Integration Tests

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore BarberBoss.sln

      - name: Subir containers com Docker Compose (override de testes)
        run: docker compose -f docker-compose.yml -f docker-compose.override.yml up -d db api
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Aguardar DB ficar pronto
        run: |
          echo "Aguardando MySQL iniciar..."
          for i in {1..15}; do
            if docker exec barberboss-mysql mysqladmin ping -h "localhost" -p${MYSQL_ROOT_PASSWORD} --silent; then
              echo "MySQL está pronto!"
              exit 0
            fi
            echo "Tentando novamente em 5s..."
            sleep 5
          done
          echo "MySQL não ficou pronto a tempo" >&2
          exit 1
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Run Integration Tests
        run: dotnet test ./tests/WebApi.Test/WebApi.Test.csproj --filter Category=Integration --verbosity normal

      - name: Derrubar containers
        if: always()
        run: docker compose -f docker-compose.yml -f docker-compose.override.yml down
