name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore BarberBoss.sln

      - name: Subir containers com Docker Compose (override de testes)
        working-directory: .
        run: |
          docker compose -f docker-compose.yml -f docker-compose.override.yml up -d

      - name: Aguardar DB ficar pronto
        run: |
          echo "Esperando o MySQL inicializar..."
          sleep 25
          docker ps -a

      - name: Run Integration Tests
        run: |
          dotnet test ./tests/UseCases.Test/UseCases.Test.csproj --filter Category=Integration --verbosity normal
          dotnet test ./tests/Validators.Tests/Validators.Tests.csproj --filter Category=Integration --verbosity normal
          dotnet test ./tests/WebApi.Test/WebApi.Test.csproj --filter Category=Integration --verbosity normal

      - name: Derrubar containers
        if: always()
        working-directory: .
        run: |
          docker compose -f docker-compose.yml -f docker-compose.override.yml down
