name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore BarberBoss.sln

      - name: Run Integration Tests
        run: dotnet test BarberBoss.sln --filter Category=Integration --no-build --verbosity normal
